server:
  port: 9001
  
#mysql setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-jbnog-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul
    username: study
    password: bitcamp123!@#
    
#JPA setting
#스키마 생성 - create: 기존 테이블 삭제 후 생성 / update: 변경된 부분만 반영
  jpa:
    hibernate:
      ddl-auto: update
#ddl 생성 시 데이터베이스 고유의 기능을 사용할 것인지?      
    generate-ddl: true
#API 호출 시 실행되는 SQL문을 콘솔에 보여줄 것인지?
    show-sql: true
#Mysql 상세 지정    
    database-platform: org.hibernate.dialect.MySQLDialect